
name: Deploy on Push
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: npm i -g --unsafe-perm --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli