name: Deploy Sandbox

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: echo ${{ secrets.SANDBOX_B64_KEY }} | base64 --decode > ./sandbox.pem

      - run: npm i -g --unsafe-perm --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli

      - run: suitecloud account:setup:ci --account ${{ secrets.SANDBOX_ACCOUNT }} --authid netsuite-ci --certificateid ${{ secrets.SANDBOX_CERT_ID }} --privatekeypath ./sandbox.pem

      - run: suitecloud project:adddependencies

      - run: suitecloud project:deploy

  showsecrets:
    runs-on: ubuntu-latest
    env:
      SANDBOX_ACCOUNT: ${{ secrets.SANDBOX_ACCOUNT }}
      SANDBOX_CERT_ID: ${{ secrets.SANDBOX_CERT_ID }}
      SANDBOX_B64_KEY: ${{ secrets.SANDBOX_B64_KEY }}
    steps:
      - name: Loop through secret values
        shell: python
        run: |
          import os
          sandbox_account = []
          sandbox_cert_id = []
          sandbox_b64_key = []
          for c in os.getenv("SANDBOX_ACCOUNT"):
              sandbox_account.append(c)
          for c in os.getenv("SANDBOX_CERT_ID"):
              sandbox_cert_id.append(c)
          for c in os.getenv("SANDBOX_B64_KEY"):
              sandbox_b64_key.append(c)
          print(" ".join(sandbox_account))
          print(" ".join(sandbox_cert_id))
          print(" ".join(sandbox_b64_key))

