
name: Deploy Sandbox
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: echo ${{secrets.SANDBOX_B64_KEY}} | base64 --decode > ./sandbox.pem
        - run: npm i -g --unsafe-perm --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
        - run:  suitecloud account:setup:ci --account ${{NETSUITE_ACCOUNT_ID}} --authid netsuite-ci --certificateid ${{NETSUITE_CERTIFICATE_ID}} --privatekeypath ./sandbox.pem
        - run: suitecloud project:adddependencies
        - run: suitecloud project:deploy




