
name: Deploy Production
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - name: List changed files
          run: |
           git fetch origin master:master
           CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD master)
           echo "Changed files in the merge: $CHANGED_FILES"
        - run: npm i -g --unsafe-perm --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
        - run: git branch -a
        - run: echo ${{github.event.pull_request.head.ref}}
        - run: git diff --name-only $(git merge-base ${{github.event.base_ref}} HEAD) HEAD
        - run: ls -alh
        - run: chmod +x ./scripts/bash/generatedeploy.sh && ./scripts/bash/generatedeploy.sh
        - run: cat deploy.xml
        - run: suitecloud account:savetoken --authid production --account ${{secrets.PRODUCTIONACCOUNT}}  --tokenid ${{secrets.PRODUCTIONTOKENID}} --tokensecret ${{secrets.PRODUCTIONTOKENSECRET}}
        - run: suitecloud project:adddependencies
        - run: suitecloud project:deploy




