
name: Deploy on Push
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: docker
    container: Dockerfile
    steps:
      - name: generate deploy.xml
        run: generatedeployxml.sh