
name: Deploy Sandbox
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
          with:
              fetch-depth: 0
        - uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - run: npm i -g --unsafe-perm --acceptSuiteCloudSDKLicense @oracle/suitecloud-cli
        - run: git branch -a
        - run: git diff --name-only $(git merge-base remotes/origin/main HEAD) HEAD
        - run: ls -alh
        - run: chmod +x ./scripts/bash/generatedeploy.sh && ./scripts/bash/generatedeploy.sh
        - run: cat deploy.xml
        - run: suitecloud account:savetoken --authid sandbox --account ${{secrets.SANDBOXACCOUNT}}  --tokenid ${{secrets.SANDBOXTOKENID}} --tokensecret ${{secrets.SANDBOXTOKENSECRET}}
        - run: suitecloud project:adddependencies
        - run: suitecloud project:deploy




